version: '3.7'

services:
  database_ignite:
    image: postgres
    container_name: coodesh_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post
      - POSTGRES_DB=coodesh
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: coodesh
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
